FROM golang:latest as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o metaplane cmd/main.go

from scratch
COPY --from=builder /app/metaplane .
CMD ["./metaplane"]